### ISSUE TITLE
请问有kaggle 题目的链接吗 想下载数据集

### ISSUE THREAD

**Issue by a1123622944** [Scottdyt/MyProject#1]

**Comment by a1123622944** [comment]
情感分析那个项目，想复现一下你的项目，但不知道数据集哪里来

**Comment by yuntaod** [comment]
@a1123622944 https://www.kaggle.com/c/word2vec-nlp-tutorial good luck！

**Comment by lemon9707** [comment]
请问Persistence文件夹下的Doc2VecArray.pkl文件有吗
